=== RealBen9/realben9.github.io/elem4sc/theme.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "definitions": {
    "color": {
      "type": "object",
      "title": "A Color Definition",
      "description": "Describes a Dynamic Color, which APIs can tweak to get an accurately themed color.",
      "required": ["color"],
      "properties": {
        "color": {
          "type": "string",
          "title": "Base Color",
          "description": "HEX or CSS color for this color entry."
        },
        "saturationMultiplier": {
          "type": "number",
          "minimum": 0,
          "title": "Saturation Multiplier",
          "description": "Limit how much the saturation slider can affect the color. 1=Full, 0=Static Color. White, Black, and Grey are forced at 0 saturation."
        },
        "lightnessMultiplier": {
          "type": "number",
          "minimum": 0,
          "title": "Lightness Multiplier",
          "description": "Limit how much the lightness slider can affect the color. 1=Full, 0=Static Color. White and Black are forced at 0 lightness, since they represent ends of the grey spectrum."
        }
      }
    },
    "sound": {
      "type": "object",
      "title": "A Sound Definition",
      "description": "Describes a Sound",
      "required": ["url"],
      "properties": {
        "url": {
          "type": "string",
          "title": "Sound URL",
          "description": "Relative or absolute url to an mp3 or wav file."
        },
        "volume": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "title": "Volume",
          "description": "Controls the volume of this sound."
        },
        "pitch": {
          "type": "number",
          "title": "Pitch",
          "description": "Controls the pitch of this sound."
        },
        "pitchVariance": {
          "type": "number",
          "title": "Pitch",
          "minimum": 0,
          "description": "Used to vary the pitch across uses. The pitch range is pitch Â±pitchVariance"
        }
      }
    }
  },
  "type": "object",
  "required": [
    "type",
    "format_version",
    "version",
    "id",
    "name"
  ],
  "properties": {
    "type": {
      "description": "Type of Elemental Data. For Elemental 4 themes it must be 'elemental4:theme'",
      "const": "elemental4:theme"
    },
    "format_version": {
      "description": "Theme format version. Must be 1",
      "const": 1
    },
    "version": {
      "title": "Theme Version",
      "description": "User set value. Used for updating.",
      "type": "number"
    },
    "id": {
      "title": "Theme Identifier",
      "description": "Unique identifier for your theme.",
      "type": "string"
    },
    "name": {
      "title": "Theme Display Name",
      "description": "Displayed in the theme menu, in bold.",
      "type": "string"
    },
    "description": {
      "title": "Theme Description",
      "description": "Displayed in the theme menu, under the theme name in smaller font.",
      "type": "string"
    },
    "author": {
      "title": "Theme Author",
      "description": "Displayed on the Workshop.",
      "type": "string"
    },
    "icon": {
      "title": "Theme Icon Path",
      "description": "Icon to be displayed next to the theme, should be 128x128. URL is resolved from this file, so it can be relative.",
      "type": "string"
    },
    "styles": {
      "title": "Theme CSS Styles",
      "description": "Theme CSS Files. URL is resolved from this file, so it can be relative.",
      "oneOf": [
        { "type": "string" },
        { "type": "array", "items": { "type": "number" }}
      ]
    },
    "sound_merge_mode": {
      "title": "Sound Merge Mode",
      "description": "Decides how sound entries from other themes should mix with this one. Combine means it will combine themes with sounds before it, Override means it will override packs before it.",
      "enum": [
        "combine",
        "override"
      ]
    },
    "colors": {
      "title": "Color Definitions",
      "description": "The Element Color Palette",
      "type": "object",
      "properties": {
        "white": { "$ref": "#/definitions/color" },
        "black": { "$ref": "#/definitions/color" },
        "grey": { "$ref": "#/definitions/color" },
        "brown": { "$ref": "#/definitions/color" },
        "red": { "$ref": "#/definitions/color" },
        "orange": { "$ref": "#/definitions/color" },
        "yellow": { "$ref": "#/definitions/color" },
        "yellow-green": { "$ref": "#/definitions/color" },
        "green": { "$ref": "#/definitions/color" },
        "aqua": { "$ref": "#/definitions/color" },
        "blue": { "$ref": "#/definitions/color" },
        "dark-blue": { "$ref": "#/definitions/color" },
        "purple": { "$ref": "#/definitions/color" },
        "magenta": { "$ref": "#/definitions/color" },
        "hot-pink": { "$ref": "#/definitions/color" }
      }
    },
    "sounds": {
      "title": "Sound Definitions",
      "description": "Sound definitions",
      "type": "object",
      "properties": {
        "element.combine": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "element.invalid": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "element.pickup": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "element.valid": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "element.valid.rediscover": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "element.drop": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "news.new-element": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "dialog.open": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "dialog.close": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "dialog.attention": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "suggest.created": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "suggest.voted": { "type": "array", "items": { "$ref": "#/definitions/sound" } },
        "startup": { "type": "array", "items": { "$ref": "#/definitions/sound"}  }
      }
    },
    "music": {
      "title": "Music",
      "description": "List of music tracks to add.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "url",
          "title",
          "author",
          "loop",
          "fade"
        ],
        "properties": {
          "url": {
            "title": "Music URL",
            "description": "Relative or Absolute URL to the song.",
            "type": "string"
          },
          "title": {
            "title": "Music Title",
            "description": "Title of the track.",
            "type": "string"
          },
          "author": {
            "title": "Music Author/Artist",
            "description": "Creator of the track.",
            "type": "string"
          },
          "volume": {
            "title": "Music Volume",
            "description": "Volume to play the track at compared to others.",
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "loop": {
            "title": "Music Loop Behavior",
            "description": "array = set loop A and B points\nloop = loop entire song\nno-loop = do not loop the song, but song may be looped if the playlist runs out",
            "oneOf": [
              {
                "enum": [
                  "loop",
                  "no-loop"
                ]
              },
              {
                "type": "array",
                "items": [{"type": "number"}],
                "minItems": 2,
                "maxItems": 2
              }
            ]
          },
          "fade": {
            "title": "Music Fade Behavior",
            "description": "no-fade = Do not fade at all.\nfade-ends = fade the start and end.\nfade-anywhere = fade can start at anywhere, best for long and ambient songs.\nfade-end = only fade end\nfade-start = only fade start",
            "enum": [
              "no-fade",
              "fade-both",
              "fade-anywhere",
              "fade-end",
              "fade-start"
            ]
          }
        }
      }
    },
    "sketch": {
      "title": "P5.js Sketch",
      "description": "Theme Sketch. Rendered with p5.js on the element game background. URL is resolved from this file, so it can be relative.",
      "type": "string"
    }
  }
}

=== RealBen9/realben9.github.io/elem4sc/themes/elem4_dark/elemental.json
{"type":"elemental4:theme","format_version":1,"version":2,"id":"elem4_dark","name":"Default Dark","author":"Dave Caruso","description":"The built in dark mode for Elemental 4.","styles":"./dark.css","icon":"./icon.png","colors":{"white":{"color":"#FFFFFF","saturationMultiplier":0,"lightnessMultiplier":0},"black":{"color":"#000000","saturationMultiplier":0,"lightnessMultiplier":0},"grey":{"color":"#7F7F7F","saturationMultiplier":0,"lightnessMultiplier":1.75},"brown":{"color":"#B58148","saturationMultiplier":0.5,"lightnessMultiplier":0.8},"red":{"color":"#E35454","saturationMultiplier":1,"lightnessMultiplier":0.8},"orange":{"color":"#E38454","saturationMultiplier":1,"lightnessMultiplier":0.8},"yellow":{"color":"#E3CB54","saturationMultiplier":1,"lightnessMultiplier":0.8},"yellow-green":{"color":"#B3E354","saturationMultiplier":1,"lightnessMultiplier":0.8},"green":{"color":"#54E360","saturationMultiplier":1,"lightnessMultiplier":0.8},"aqua":{"color":"#54E3B3","saturationMultiplier":1,"lightnessMultiplier":0.8},"blue":{"color":"#54b3e3","saturationMultiplier":1,"lightnessMultiplier":0.8},"dark-blue":{"color":"#5475e3","saturationMultiplier":1,"lightnessMultiplier":0.8},"purple":{"color":"#8654E3","saturationMultiplier":1,"lightnessMultiplier":0.8},"magenta":{"color":"#D054E3","saturationMultiplier":1,"lightnessMultiplier":0.8},"hot-pink":{"color":"#E354A2","saturationMultiplier":1,"lightnessMultiplier":0.8}}}
